name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-laravel:
    uses: ./.github/workflows/laravel.yml@main
  call-lumen:
    uses: ./.github/workflows/lumen.yml@main
  call-slim:
    uses: ./.github/workflows/slim.yml@main
