name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-laravel:
    uses: DerManoMann/openapi-router/.github/workflows/laravel.yml@php81-attributes
  call-lumen:
    uses: DerManoMann/openapi-router/.github/workflows/lumen.yml@php81-attributes
  call-slim:
    uses: DerManoMann/openapi-router/.github/workflows/slim.yml@php81-attributes
