name: slim

on:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        slim: [ '4.0' ]
        dependencies: [ 'lowest', 'highest' ]
        exclude:
          - php: '8.1'
            slim: '3.2'
          - php: '8.1'
            dependencies: 'lowest'

    name: PHP ${{ matrix.php }} / Slim ${{ matrix.slim }} on ${{ matrix.operating-system }} with ${{ matrix.dependencies }} dependencies

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install framework deps
        run: |
          composer require --dev slim/slim "^${{ matrix.slim }}" -W

      - name: Composer install
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: PHPUnit + Code coverage
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
